### ISSUE TITLE
Migrate stagei into quarterback

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/quarterback#89]
# Migrate stagei into quarterback

## Problem

stagei’s causing issues and outages in the COINS ecosystem due to its poor implementation of file downloads. The server’s old and not easily reproducible by ops.

## Solution

The current application code, found in [MRN-Code/dataDownloadCenter](https://github.com/MRN-Code/dataDownloadCenter), should be ported to JavaScript and moved into the monorepo. The new code should duplicate the old app’s functionality 100% such that we can replace current stagei without rewriting Data Exchange front-end code. This new application should function similar to _steelpenny_: installed as a global module by NPM and run through an upstart script (or systemd, depending on where we are on Ubuntu 16.04 setup). The new service should be wired up behind nginx, which should handle HTTP → HTTPS redirects (PHP application code currently manually redirects).

I’ve created a new package on the `feature/change-dispenser`, located in _packages/change-dispenser_. The branch currently contains a base project structure with loosely structured integration tests. Please work off this branch.

## Tasks

- [ ] Finish writing integration tests. The main holes lie in stubbing requests in the database on test setup, then removing the stubs on test teardown.
- [ ] Write unit tests for the application code.
- [ ] Write application code to pass tests. To reduce memory overhead, consider using streams send files to clients:

    ```js
    const fs = require('fs');

    // http request listener
    function handler(req, res) {
      res.writeHead(200, {
        'Content-Type': 'application/zip',
      });
      fs.createReadStream('./path/to/file.zip').pipe(res);
    }
    ```
- [ ] Ensure database connections are pooled. Might be cool to make a test for this!
- [ ] Examine stagei for crons, stored data and other application code. Ensure it’s okay to completely rebuild the server from scratch.
- [ ] Collaborate with @zombieprocess to ensure reproducible builds of a new stagei server.
